[server]
enableXsrfProtection = false

[theme]
font = "Poppins:https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
codeFont = "'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"
primaryColor = "black"
backgroundColor = "#F9F9F9F9"
